name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia
  workflow_dispatch:   # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: WJESUSS
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar animação
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
